services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: ederevxus-app:latest
    volumes:
      - app_storage:/var/www/html/storage
      - app_dbdata:/var/www/html/database/data
    restart: unless-stopped

  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    depends_on:
      - app
      - phpmyadmin
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      - PMA_SOCKET=/run/mysqld/mysqld.sock
      - PMA_ABSOLUTE_URI=https://${SERVER_IP}/phpmyadmin/
    volumes:
      - /run/mysqld:/run/mysqld:ro
    restart: unless-stopped

volumes:
  app_storage:
  app_dbdata:
